### ISSUE TITLE
请问为什么翻译最后显示 translation success，但是生成的文件里面和源文件一模一样

### ISSUE THREAD

**Issue by LiuZhe6** [jinguangyue/AndroidStringsOneTabTranslation#1]
请问为什么翻译最后显示 translation success，但是生成的文件里面和源文件一模一样

**Comment by jinguangyue** [comment]
多谢反馈， 我最近使用也发现了这个问题， 尤其是翻译数量过多的时候， 你可以先只翻译出问题的语言试试， 我会尽快修复

**Comment by LiuZhe6** [comment]
那我先试试分批翻译吧，让他一次性翻译量少一点

**Comment by LiuZhe6** [comment]
请问还有没有其他插件呢或者其他方法？我之前使用AndroidLocalizationer抛出空指针异常。

**Comment by jinguangyue** [comment]
我是改的AndroidLocalizationer  目前没搜索到其他插件 最好的方式就是自己改 有什么问题自己修复

**Comment by dongweiq** [comment]
这个问题修复了吗

**Comment by dongweiq** [comment]
我测试后发现如果apikey填错会翻译不成功，但是文件还是会生成，但是填对了后翻译的全是乱码，类似于以下这种
`	<string name="setting_page">% E8% AE% WEES% E7% BD% AE% E9% A1% B5% E9% 9D% A2</string>
	<string name="cruise_page">% E5% B7% A1% E6% B8% B8% E8% B7% AF% E7% BA% BF</string>
	<string name="point_page">% E7% 82% B9% E4% BD% 8D% E4% BF% A1% E6% 81% AF</string>
	<string name="main_add_zone">% E6% B7% BB% E5% 8A% A0% E5% 8C% BA% E5% 9F% 9F</string>`

**Comment by jinguangyue** [comment]
> 我测试后发现如果apikey填错会翻译不成功，但是文件还是会生成，但是填对了后翻译的全是乱码，类似于以下这种
> `	<string name="setting_page">% E8% AE% WEES% E7% BD% AE% E9% A1% B5% E9% 9D% A2</string> <string name="cruise_page">% E5% B7% A1% E6% B8% B8% E8% B7% AF% E7% BA% BF</string> <string name="point_page">% E7% 82% B9% E4% BD% 8D% E4% BF% A1% E6% 81% AF</string> <string name="main_add_zone">% E6% B7% BB% E5% 8A% A0% E5% 8C% BA% E5% 9F% 9F</string>`

key 肯定不能填错啊
