### ISSUE TITLE
com.intellij.diagnostic.PluginException: class with name 'action.ConvertToOtherLanguages' not found [Plugin: AndroidStringsOneTabTranslation]

### ISSUE THREAD

**Issue by Abvatous** [jinguangyue/AndroidStringsOneTabTranslation#8]
Hey~Guy~
As my title said,I met a confused question when I clicked（right_click）to use the Plugin.
Unfortunely,a error accoured :
class with name 'action.ConvertToOtherLanguages' not found [Plugin: AndroidStringsOneTabTranslation]
com.intellij.diagnostic.PluginException: class with name 'action.ConvertToOtherLanguages' not found [Plugin: AndroidStringsOneTabTranslation].
Thyou~~

**Comment by jinguangyue** [comment]
Maybe a configuration problem. You can query “How to configure android studio plugin”.

**Comment by Abvatous** [comment]
The verison of AS：3.0.1，JDK:1.8.98
Did you mean  should check my  Plugin import? 
![image](https://user-images.githubusercontent.com/20251065/45727474-755a4800-bbf6-11e8-92b9-8fa70a91f907.png)

But maybe I met a puzzed one.I imported the Plugin ,But it did not  work as I hoped~~
![image](https://user-images.githubusercontent.com/20251065/45727597-00d3d900-bbf7-11e8-8e7a-480b5375e92b.png)

**Comment by jinguangyue** [comment]
Can you access google.com?

**Comment by Abvatous** [comment]
Hah~I solved it by reinstalling serveral times,maybe something wrong in my broken computer.
Thank you very much~
